all:
  hosts:
    node1:
      ansible_host: 10.106.0.2
      ip: 10.106.0.2
      access_ip: 10.106.0.2
    node2:
      ansible_host: 10.106.0.3
      ip: 10.106.0.3
      access_ip: 10.106.0.3
    node3:
      ansible_host: 10.106.0.4
      ip: 10.106.0.3
      access_ip: 10.106.0.3
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
